# RAG-Factory 配置文件 (适配2wikimultihopqa数据集)
dataset:
 dataset_name: test_samples
 n_samples: 10
 chunk_size: 1024 # 每个chunk包含的token数  
 chunk_overlap: 20 # 每个chunk之间的重叠token数

llm:
  type: OpenAICompatible
  base_url: "http://192.168.190.3:9997/v1"
  api_key: "not used actually"
  model: "qwen2.5-instruct"

embedding:
  type: OpenAICompatibleEmbedding
  base_url: "http://192.168.190.3:9997/v1"
  api_key: "not used actually"
  model: "jina-embeddings-v3"
  dimension: 1024

storage:
  type: vector_store
  url: "http://192.168.190.3:6333"


rag:
  solution: "naive_rag"
  mode: None
  num_workers: 4 # 并行处理chunk的worker数
  similarity_top_k: 10 # 检索到的top_k个节点
  stages: ["create", "inference","evaluation"]
