llm:
  name: openai
  base_url: "xxx"
  api_key: "xxx"
  model: "gpt-4.1-mini"

embedding:
  name: huggingface
  model_name: "xxx"
  model_kwargs:
    device: "cuda:0"



store:
  name: faiss
  folder_path: xxx


bm25:
  name: bm25
  k: 10
  data_path: xxx

retriever:
  name: vectorstore

reranker:
  name: qwen3
  model_name_or_path: "xxx"
  device_id: "cuda:0"

dataset:
  name: TCL
  
